repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: debug-statements
    -   id: check-yaml
    -   id: check-ast
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
        args:
            - "--line-length=120"
            - "--skip-magic-trailing-comma"
            - "--preview"

-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        args: [--max-line-length=120]

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-use-type-annotations
